In [1]:
import pandas as pd
import requests
import numpy as np
from pathlib import Path
from constant import accounting_path, monthly_price_path
from src.PPP.input_generator import generator
from src.Proposed_Model.data_generator import generator
from scipy.stats import kendalltau
from src.Proposed_Model.utils.dependence_structure import kendall_matrix, cross_section_order
from src.Proposed_Model.utils.elicitation import parameter_derived
from pyvinecopulib import BicopFamily
from constant import monthly_FF5_path

In [8]:
df = generator()
df[0].iloc[0,0]

np.float64(0.16957398397145193)

In [11]:
ff5_df = pd.read_csv(monthly_FF5_path)
ff5_df['date'] = ff5_df['date'].apply(lambda x: str(x))
ff5_df['date'] = ff5_df['date'].apply(lambda x: f'{x[:4]}-{x[4::]}-01')
ff5_df['date'] = pd.to_datetime(ff5_df['date'])+pd.offsets.MonthEnd()
ff5_df.set_index('date',inplace=True)

In [12]:
ff5_df.columns

Index(['Mkt-RF', 'SMB', 'HML', 'RMW', 'CMA', 'RF'], dtype='str')

In [28]:
T = 100
d = 3
N = 5

X = np.random.randn(T, d)
Y = np.random.randn(T, N)

X1 = np.hstack([np.ones(T).reshape(-1,1),X])

np.linalg.lstsq(X1, Y, rcond=None)


# (4, 5)

(array([[ 0.08069365,  0.13035645,  0.23552937,  0.11374137, -0.02603407],
        [-0.11597772, -0.00791827,  0.00165453, -0.03660562, -0.13384025],
        [ 0.03889275,  0.11259486, -0.18930212,  0.06865107, -0.02849307],
        [ 0.10113684, -0.08925749,  0.24437936, -0.0472556 ,  0.02611772]]),
 array([88.17644248, 72.40348891, 92.98501282, 80.61066503, 81.83620198]),
 np.int32(4),
 array([11.89637102, 10.28027908,  9.84879897,  9.17246769]))

In [4]:
a = np.ones(shape=(3,3))
a[:,None,:].shape

(3, 1, 3)

In [17]:
X1.shape

(100, 4)

In [38]:
ar = np.ones(shape=(3,4,5))
np.cumsum(ar[0],axis=0)

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [37]:
ar[0]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.maximum